<?php

/**
 * @file
 * Defines simple country field type.
 */

use Symfony\Component\HttpFoundation\Request;

/**
 * Implements hook_help().
 */
function country_help($route_name, Request $request) {
  switch ($route_name) {
    case 'help.page.country':
      $output = '';
      $output .= '<h3>' . t('Country') . '</h3>';
      $output .= '<p>' . t('The Country module defines a simple country field type for the Field module. It provides 2 widgets - select options and autocomplete textfield - for this purpose.  See the <a href="!field-help">Field module help page</a> for more information about fields.', array('!field-help' => url('admin/help/field_ui'))) . '</p>';
      return $output;
  }
}

/**
 * Form element validate handler for country autocomplete element.
 */
function country_autocomplete_validate($element, &$form_state) {
  if ($country = $element['#value']) {
    $countries = \Drupal::service('country_manager')->getList();
    $iso2 = array_search($country, $countries);
    if (!empty($iso2)) {
      \Drupal::formBuilder()
        ->setValue($element, array(
            'value' => $iso2,
            'label' => $country
          ), $form_state);
    }
  }
}
